# Generated by Django 2.2.5 on 2022-07-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(default='', max_length=50)),
                ('item_price', models.FloatField(default=0)),
                ('quantity_ordered', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Ingredients')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MenuItems')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('purchase_timestamp', models.DateField()),
                ('purchase_price', models.FloatField(default=0)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Ingredients')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MenuItems')),
                ('recipe_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.RecipeRequirements')),
            ],
        ),
    ]
