# Generated by Django 2.2.5 on 2022-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recipe_requirements',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(default='oz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
