# Generated by Django 2.2.5 on 2022-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220720_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reciperequirements',
            name='ingredient_quantity',
            field=models.FloatField(default=0),
        ),
    ]
