# Generated by Django 2.2.5 on 2022-08-04 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220731_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_timestamp',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 7, 12, 47, 739372)),
        ),
    ]
