# Generated by Django 2.2.5 on 2022-08-18 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220818_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_timestamp',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 5, 16, 9, 762337)),
        ),
        migrations.AlterField(
            model_name='timedstrings',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 5, 16, 9, 762556)),
        ),
    ]
